env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_conf: ""

task:
  name: master
  timeout_in: 2h
  container:
    image: dopaemon/nitdroid:latest
    cpu: 8
    memory: 8G

  Install_Packages_Ubuntu_script:
    - rm -rf *
    - sudo apt-get update
    - sudo apt-get -y install libswitch-perl
  Rclone_Configure_script:
    - mkdir -p ~/.config/rclone
    - echo "$rclone_conf" > ~/.config/rclone/rclone.conf
  Compile_Kernel_script:
    - git clone -b CirrusCI https://github.com/Nitdroid-Reborn/CI.git /tmp/ci/run
    - cd /tmp/ci/run
    - export CCACHE_DIR=/tmp/ccache
    - export CCACHE_EXEC=$(which ccache)
    - export USE_CCACHE=1
    - ccache -M 20G
    - ccache -z
    - chmod +x build.sh
    - ./build.sh

