version: 2.1
jobs:
  Nitdroid-Reborn:
   docker:
      - image: dopaemon/nitdroid:latest
   steps:
      - run:
          name: Disk Info
          no_output_timeout: 20m
          command: |
            lscpu
            df -h
      - run:
          name: Packages
          no_output_timeout: 20m
          command: |
            sudo apt-get update
            sudo apt-get -y install libswitch-perl
      - run:
          name: Repo
          no_output_timeout: 20m
          command: |
            sudo apt-get update && sudo apt-get install wget -y
            mkdir ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            git config --global http.sslVerify false
      - run:
          name: Java
          no_output_timeout: 20m
          command: |
            java -version
            wget https://github.com/Nitdroid-Reborn/CI/releases/download/Java-Oracle-6u45/jdk-6u45-linux-x64.bin
            chmod +x jdk-6u45-linux-x64.bin
            ./jdk-6u45-linux-x64.bin
            sudo mv jdk1.6.0_45 /usr/lib/jvm/
            sudo ln -sf /usr/lib/jvm/jdk1.6.0_45/bin/java /usr/bin/java
            sudo ln -sf /usr/lib/jvm/jdk1.6.0_45/bin/javac /usr/bin/javac
            sudo ln -sf /usr/lib/jvm/jdk1.6.0_45/bin/javaws /usr/bin/javaws
            java -version
            export JAVA_HOME="/usr/lib/jvm/jdk1.6.0_45"
      - run:
          name: Python
          no_output_timeout: 20m
          command: |
            sudo apt-get update
            sudo apt-get install software-properties-common -y
            sudo add-apt-repository --yes ppa:fkrull/deadsnakes
            sudo apt-get update
            sudo apt-get install python3.6 python2.7 -y
            sudo ln -sf python3.6 /usr/bin/python
            python --version
      - run:
          name: Repo Sync
          no_output_timeout: 20m
          command: |
            mkdir -p ~/Nitdroid && cd ~/Nitdroid
            python3.6 ~/bin/repo init -u https://github.com/Nitdroid-Reborn/nitdroid_platform_manifest.git -b jb
            python3.6 ~/bin/repo sync -v -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
      - run:
          name: Build
          no_output_timeout: 20m
          command: |
            export JAVA_HOME="/usr/lib/jvm/jdk1.6.0_45"
            sudo ln -sf python2.7 /usr/bin/python
            cd ~/Nitdroid
            source build/envsetup.sh
            lunch n9-userdebug
            make j$(nproc --all)
workflows:
  version: 2.1
  cooking:
    jobs:
      - Nitdroid-Reborn
