version: 2.1
jobs:
  Nitdroid-Reborn:
   docker:
      - image: dopaemon/nitdroid:latest
   steps:
      - run:
          name: Disk Info
          no_output_timeout: 20m
          command: |
            lscpu
            df -h
      - run:
          name: Repo
          no_output_timeout: 20m
          command: |
            sudo apt-get update && sudo apt-get install wget -y
            mkdir ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
      - run:
          name: Python 2.7
          no_output_timeout: 20m
          command: |
            sudo apt-get update
            sudo apt-get install software-properties-common -y
            sudo add-apt-repository --yes ppa:fkrull/deadsnakes
            sudo apt-get update
            sudo apt-get install python3 -y
            sudo ln -sf python3 /usr/bin/python
            python --version
      - run:
          name: Repo Sync
          no_output_timeout: 20m
          command: |
            mkdir -p Nitdroid && cd Nitdroid
            python3 ~/bin/repo init -u git://gitorious.org/android-n900/nitdroid_platform_manifest.git -b ics
            python3 ~/bin/repo sync -j$(nproc --all)
      - run:
          name: Setup CCACHE
          no_output_timeout: 20m
          command: |
            echo "ccache -M 50G" > ~/.bashrc
            echo "ccache -o compression=true" > ~/.bashrc
            ccache -M 50G
            ccache -o compression=true
      - run:
          name: Disk Info
          no_output_timeout: 20m
          command: |
            lscpu
            df -h
            java -version
workflows:
  version: 2.1
  cooking:
    jobs:
      - Nitdroid-Reborn
