version: 2.1
jobs:
  Nitdroid-Reborn:
   docker:
      - image: dopaemon/nitdroid:latest
   steps:
      - run:
          name: Disk Info
          no_output_timeout: 20m
          command: |
            lscpu
            df -h
      - run:
          name: Repo
          no_output_timeout: 20m
          command: |
            sudo apt-get update && sudo apt-get install wget -y
            mkdir ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            git config --global http.sslVerify false
      - run:
          name: Java
          no_output_timeout: 20m
          command: |
            java --version
      - run:
          name: Python 3.6
          no_output_timeout: 20m
          command: |
            sudo apt-get update
            sudo apt-get install software-properties-common -y
            sudo add-apt-repository --yes ppa:fkrull/deadsnakes
            sudo apt-get update
            sudo apt-get install python3.6 -y
            sudo ln -sf python3.6 /usr/bin/python
            python --version
      - run:
          name: Repo Sync
          no_output_timeout: 20m
          command: |
            mkdir -p /tmp/Nitdroid && cd /tmp/Nitdroid
            python3.6 ~/bin/repo init -u https://github.com/Nitdroid-Reborn/nitdroid_platform_manifest.git -b jb
            python3.6 ~/bin/repo sync -j$(nproc --all)
      - run:
          name: Build
          no_output_timeout: 20m
          command: |
            cd /tmp/Nitdroid
            source build/envsetup.sh
            lunch n9-userdebug
            make j$(nproc --all)
workflows:
  version: 2.1
  cooking:
    jobs:
      - Nitdroid-Reborn
